# Basics 
## (a)

In [4]:
x = "pangolin"
y = set(x)

try: y[1] == "p" # (i)
except: print("hip")
try: x[1] = "s" # (ii)
except: print("hep")
if len(y) == len(x): # (iii)
    print("hop")

hip
hep


In [5]:
print(x)
print(y) # no duplicates allowed in set

pangolin
{'o', 'i', 'g', 'l', 'n', 'p', 'a'}


In [3]:
y[1] == "p" # (i)

TypeError: 'set' object is not subscriptable

In [6]:
x[1] = "s" #(ii)

TypeError: 'str' object does not support item assignment

In [7]:
len(y) == len(x) # (iii)

False

### Remarks:
- Different python objects:
| Feature               | List          | Tuple         | Set           | Dictionary   |
|-----------------------|---------------|---------------|---------------|--------------|
| **Example**     |```[1, 2, 3]```|```(1, 2, 3)```|```{1, 2, 3}```|```{"key1": 1, "key2": 2}```|
| **Mutable**           | Yes           | No            | Yes (add or remove, but not change)| Yes          |
| **Ordered**           | Yes           | Yes           | No            | Yes (since Python 3.7) |
| **Allows Duplicates**  | Yes           | Yes           | No            | Keys: No, Values: Yes |
| **Indexed**           | Yes           | Yes           | No            | Keys         |
| **Usage**             | General collection | Immutable collection | Unique elements | Key-value mapping |
- try (A) except (B): If any error during (A) then print (B). (If (A) has no errors then nothing is printed out, unless (A) asks to print the output explicitly.)


## (b)

In [8]:
def f(x, y = 2): x if y < 1 else x - y # function with no return (output)
x = [f(x, i) for i, x in enumerate((1, 2))]
print(type(x), str(x))

<class 'list'> [None, None]


In [9]:
f

<function __main__.f(x, y=2)>

In [10]:
x

[None, None]

In [12]:
# enumerate
print(list(enumerate((1, 2))))
for i, x in enumerate((1, 2)):
    print(i, x)

[(0, 1), (1, 2)]
0 1
1 2


## (c)

In [47]:
x = (i for i in range(3))
y = [i for i in x if i < 2]
z = list(x)

print(type(x))
print(type(z), str(z))

<class 'generator'>
<class 'list'> []


In [48]:
print(x)
print(y)
print(z)

<generator object <genexpr> at 0x7fa9e748e890>
[0, 1]
[]


In [49]:
# generators can only be used once; this is why z was an empty list above.
x = (i for i in range(3))
z = list(x)
print(z)

[0, 1, 2]


## (d)

In [50]:
f = lambda n: 1 if n==0 else n*f(n-1) # n factorial (n \ge 0)

try: f(4.0) # (i)
except: print("hip")
try: f(-1) # (ii)
except: print("hep")

hep


In [51]:
f(4.0)

24.0

In [52]:
f(-1)

RecursionError: maximum recursion depth exceeded in comparison

## (e)

In [75]:
x = (2, 3)[:1]
y = {2: 3, 3: x, x: 2}
del x

In [76]:
x = (2, 3)[:1] # ends right before index 1
y = {2: 3, 3: x, x: 2}
print(x) # tuple with one element; not collapsed to int
del x
print(y)

(2,)
{2: 3, 3: (2,), (2,): 2}


In [78]:
print(y[(2,)] == y.get(2))
print(y[(2,)])
print(y.get(2)) # get values of key 2
######
try: y[(2,)] == y.get(2) # (i)
except: print('hip')

False
2
3


In [79]:
try: y[3.0] = 'hep' # (ii)
except: print('hep')

In [81]:
try: y[x] = 3 # (iii)
except: print('hop')
y[x] = 3

hop


NameError: name 'x' is not defined

# Memory
## (a)

In [82]:
from copy import deepcopy

x = [{'quiche': 4}, 444, 4.0, 'quiche']
y = x.copy()
z = deepcopy(x)

print([i is j for i,j in zip(x, y)]) # (i); Shallow copy
print([i is j for i,j in zip(x, z)]) # (ii); Deep copy

[True, True, True, True]
[False, True, True, True]


- ```copy```: Creating new object that shares the reference
- ```deepcopy```: Creating new object that recursively ```copy```
- Reference Semantics: A list is a collection of references

In [83]:
list1 = [[1, 10000], 20000, 3]
list2 = [[1, 10000], 20000, 3]
list3 = list1
list4 = list1.copy()
list5 = deepcopy(list1)

# General comparison
print(list1 is list2) # new object (but with the same value)
print(list1 is list3) # assign; same object
print(list1 is list4) # copy: new object
print(list1 is list5) # deepcopy: new object

False
True
False
False


In [84]:
# Nonnested comparison: No interning
print(list1[1] is list2[1])
print(list1[1] is list3[1])
print(list1[1] is list4[1]) # copy: same reference
print(list1[1] is list5[1]) # deepcopy: acts like copy in non-nested object (recursive copy)

False
True
True
True


In [87]:
# Nonnested comparison: Interning
print(list1[2] is list2[2])
print(list1[2] is list3[2])
print(list1[2] is list4[2]) 
print(list1[2] is list5[2]) 

True
True
True
True


In [85]:
# Nested comparision
print(list1[0] is list2[0]) # new object (but with the same value)
print(list1[0] is list3[0]) # assign; same object
print(list1[0] is list4[0]) # copy: use the same reference so same object,
### Everything within is the same (see below)
print(list1[0] is list5[0]) # deepcopy: new object that shares the reference (see below)

False
True
True
False


In [86]:
print(list1[0][1] is list2[0][1]) 
print(list1[0][1] is list3[0][1]) 
print(list1[0][1] is list4[0][1]) 
print(list1[0][1] is list5[0][1]) # deepcopy: recursive copy; in the nested elements, same reference, same object

False
True
True
True


## (b)

In [88]:
x = ['dreams', {3, 4}, None, '!']
try: y = ('dreams', {4, 3}, None, x)
except: print('hip')
try: x[x.index('!')] = y
except: print('hep')
try: 
    if x[3][3] is x: print('hop')
except: print('hup')

hop


In [89]:
x = ['dreams', {3, 4}, None, '!']
x

['dreams', {3, 4}, None, '!']

In [90]:
y = ('dreams', {4, 3}, None, x)
y

('dreams', {3, 4}, None, ['dreams', {3, 4}, None, '!'])

In [91]:
x[x.index('!')] = y
x

['dreams', {3, 4}, None, ('dreams', {3, 4}, None, [...])]

In [92]:
x[3][3] is x

True

## (c)

In [93]:
import sys 

f = lambda: sys.intern('purple turtle')
x = f()
y = x, f(),'purple turtle'
del x
z = f()

print([z is i for i in y])

[True, True, False]


# Numpy and pandas
## (a)

In [94]:
import numpy as np

x = np.array([int('1'), 1.4])
if isinstance(x[0], int): print('hep')
if isinstance(x[0], float): print('hip')
if isinstance(x[0], str): print('hop')

hip


In [95]:
x

array([1. , 1.4])

In [96]:
x[0]

1.0

## (b)

In [97]:
x = np.array([[[1], [2.0], [4.1]], 
              [[2.1], [3], [None]]])
y = np.matrix(x[0])


print(x.shape) # (i); Count from the outside
print(y.shape) # (ii)

(2, 3, 1)
(3, 1)


In [99]:
print(x)
print(y)

[[[1]
  [2.0]
  [4.1]]

 [[2.1]
  [3]
  [None]]]
[[1]
 [2.0]
 [4.1]]


## (c)

In [100]:
x = np.array([[3, 2, 4.0], [0, -4, 1]])

try: (x - 3) + x
except: print('hep')
try: x + np.transpose([[1, 2.0], [3, 4], [3, 4]])
except: print('hip')
try: x[:2,0] @ [1, 2.0]
except: print('hop')

In [101]:
x

array([[ 3.,  2.,  4.],
       [ 0., -4.,  1.]])

In [102]:
(x - 3) + x # elementwise operation for not-matching-dimension

array([[  3.,   1.,   5.],
       [ -3., -11.,  -1.]])

In [103]:
x + np.transpose([[1, 2.0], [3, 4], [3, 4]])

array([[4., 5., 7.],
       [2., 0., 5.]])

In [106]:
x[:2,0] @ [1, 2.0]  # matrix multiplication

3.0

## (d)

In [107]:
import pandas as pd

x = pd.Series([1,2,0,3], index = [2, 1, 0, 4])

print([x[2], x.iloc[2], x.loc[2]]) #loc: labels, iloc: locations

[1, 0, 1]


In [108]:
x

2    1
1    2
0    0
4    3
dtype: int64

## (e)

In [109]:
y = x.reset_index()
y = y.rename(columns = {'index': 'A', 0: 'B'})

try: z = y.iloc[:,1] * x / 3 # (i)
except: print('hip')
try: y['C'] = z # (ii)
except: print('hep')
    
print([type(y.iloc[0,i]) for i in range(y.shape[1])])  # (iii)

[<class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.float64'>]


In [110]:
y = x.reset_index()
y = y.rename(columns = {'index': 'A', 0: 'B'})
y

A  B
0  2  1
1  1  2
2  0  0
3  4  3

In [111]:
y.iloc[:,1]

0    1
1    2
2    0
3    3
Name: B, dtype: int64

In [112]:
x

2    1
1    2
0    0
4    3
dtype: int64

In [113]:
y.iloc[:,1] * x # 0*0, 2*2, 0*1, 3*NaN(x[3] doesn't exist), Nan*3(y[4] doesn't exist)

0    0.0
1    4.0
2    0.0
3    NaN
4    NaN
dtype: float64

In [114]:
z = y.iloc[:,1] * x / 3
z

0    0.000000
1    1.333333
2    0.000000
3         NaN
4         NaN
dtype: float64

In [115]:
y['C'] = z ## (ii)
y

A  B         C
0  2  1  0.000000
1  1  2  1.333333
2  0  0  0.000000
3  4  3       NaN

In [116]:
z

0    0.000000
1    1.333333
2    0.000000
3         NaN
4         NaN
dtype: float64